apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: capstone1
data:
  DB_HOST: mysql
  DB_USER: root
  DB_NAME: tododb
  PORT: "5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: capstone1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 082846230300.dkr.ecr.ap-south-1.amazonaws.com/capstone1-backend:6
          ports:
            - containerPort: 5000
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: mysql-secret
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: capstone1
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000